from typing import List, TypedDict

class WorkflowState(TypedDict):
    # Define the structure of the workflow state

    # The topic of the workflow, e.g., "data_analysis", "content_generation", etc.
    topic: str

    # Research question or task description that the workflow is designed to address
    research: str

    # The current draft or output generated by the workflow
    draft: str

    # Critique or feedback about the current draft
    critique: str
    
    # A list of suggestions for improving the draft based on the critique 
    revision_count: int

    # Final output after revisions, if applicable 
    final_output: str
    
    # List of messages exchanged between agents, can be of any type (e.g., dict, str, etc.)
    messages: List[str]